# Generated by Django 3.1.7 on 2021-06-08 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lom_antennas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lom_telekom', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('akb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('chernmet', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lom_copper', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('performer_document', models.FileField(upload_to='performer_acts/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='acts/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('representative', models.CharField(max_length=50)),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('receive_date', models.DateField(blank=True, null=True)),
                ('antennas_weight', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('telekom_weight', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('akb_weight', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('iron_weight', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('cable_weight', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('city', models.CharField(max_length=50)),
                ('document', models.FileField(upload_to='acts/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=None)),
                ('initiator_name', models.CharField(max_length=50)),
                ('initiator_phone', models.CharField(max_length=50)),
                ('initiator_representative', models.CharField(max_length=50)),
                ('accepted_date', models.DateField(default=None, null=True)),
                ('acceptor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.answer')),
                ('performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.performer')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.requisition')),
            ],
        ),
    ]
