# Generated by Django 3.1.7 on 2021-06-08 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('organization', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='customer/%Y/%m/%d')),
                ('email', models.EmailField(db_index=True, max_length=200)),
                ('phone', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cvetmet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='cvetmet/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=200)),
                ('category', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Raddet_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='raddet/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'raddet_category',
                'verbose_name_plural': 'raddet_categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Recycling',
            fields=[
                ('FkkoCode', models.CharField(db_index=True, default=None, max_length=20, primary_key=True, serialize=False)),
                ('FkkoDescription', models.TextField(blank=True, max_length=300)),
                ('collection', models.BooleanField(default=False)),
                ('transportation', models.BooleanField(default=False)),
                ('processing', models.BooleanField(default=False)),
                ('disposal', models.BooleanField(default=False)),
                ('utilization', models.BooleanField(default=False)),
                ('placement', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Raddet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='raddet/%Y/%m/%d')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('retail', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('opt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vtormet.raddet_category')),
            ],
        ),
    ]
