# Generated by Django 4.0.2 on 2022-02-20 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtormet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raddet_category',
            options={},
        ),
    ]
