# Generated by Django 4.0.2 on 2022-03-09 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vtormet', '0003_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_number', models.CharField(db_index=True, max_length=50)),
                ('serial_number', models.CharField(db_index=True, max_length=50)),
                ('sap_material', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('quantity', models.IntegerField()),
                ('comment', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_in', models.CharField(db_index=True, default=None, max_length=50)),
                ('number_out', models.CharField(db_index=True, default=None, max_length=50)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(default=None)),
                ('end_date', models.DateTimeField(default=None)),
                ('city', models.CharField(db_index=True, default=None, max_length=50)),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('requisition_item', models.ManyToManyField(default=None, to='vtormet.RequisitionItem')),
            ],
        ),
    ]
