# Generated by Django 4.0.2 on 2022-04-13 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vtormet', '0006_remove_requisition_auction_bid_requisition_bid_sum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_sum', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vtormet.customer')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vtormet.requisition')),
            ],
        ),
    ]
